#!/bin/bash
set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_INSTALL_PATH="$HOME/swahn"

echo "🚀 Setting up dotfiles from $DOTFILES_DIR"
echo ""

# Prompt for install path
read -p "📁 Install path [$DEFAULT_INSTALL_PATH]: " INSTALL_PATH
INSTALL_PATH="${INSTALL_PATH:-$DEFAULT_INSTALL_PATH}"
INSTALL_PATH="${INSTALL_PATH/#\~/$HOME}"  # Expand tilde

echo "   Installing to: $INSTALL_PATH"
mkdir -p "$INSTALL_PATH"

# Install zsh if not present
if ! command -v zsh &> /dev/null; then
    echo "📦 Installing zsh..."
    if command -v apt &> /dev/null; then
        sudo apt update && sudo apt install -y zsh
    elif command -v dnf &> /dev/null; then
        sudo dnf install -y zsh
    elif command -v pacman &> /dev/null; then
        sudo pacman -S --noconfirm zsh
    elif command -v brew &> /dev/null; then
        brew install zsh
    else
        echo "❌ Could not detect package manager. Please install zsh manually."
        exit 1
    fi
else
    echo "✓ zsh already installed"
fi

# Install oh-my-zsh if not present
ZSH_DIR="$INSTALL_PATH/.oh-my-zsh"
if [ ! -d "$ZSH_DIR" ]; then
    echo "📦 Installing oh-my-zsh..."
    ZSH="$ZSH_DIR" sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc
else
    echo "✓ oh-my-zsh already installed"
fi

# Install zsh-autosuggestions plugin
ZSH_CUSTOM="$ZSH_DIR/custom"
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]; then
    echo "📦 Installing zsh-autosuggestions..."
    git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
else
    echo "✓ zsh-autosuggestions already installed"
fi

# Install zsh-syntax-highlighting plugin
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ]; then
    echo "📦 Installing zsh-syntax-highlighting..."
    git clone https://github.com/zsh-users/zsh-syntax-highlighting "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
else
    echo "✓ zsh-syntax-highlighting already installed"
fi

# Install starship if not present
STARSHIP_BIN="$INSTALL_PATH/bin/starship"
if [ ! -f "$STARSHIP_BIN" ]; then
    echo "📦 Installing starship..."
    mkdir -p "$INSTALL_PATH/bin"
    curl -sS https://starship.rs/install.sh | sh -s -- --yes --bin-dir "$INSTALL_PATH/bin"
else
    echo "✓ starship already installed"
fi

# Backup existing configs
backup_if_exists() {
    if [ -f "$1" ] && [ ! -L "$1" ]; then
        echo "📋 Backing up $1 to $1.backup"
        mv "$1" "$1.backup"
    fi
}

backup_if_exists "$HOME/.zshrc"
backup_if_exists "$HOME/.zshenv"
backup_if_exists "$HOME/.config/starship.toml"

# Create zshenv with install path
echo "📝 Creating ~/.zshenv..."
cat > "$HOME/.zshenv" << EOF
# Dotfiles install path (auto-generated by setup.sh)
export DOTFILES_PATH="$INSTALL_PATH"
export ZSH="\$DOTFILES_PATH/.oh-my-zsh"
export PATH="\$DOTFILES_PATH/bin:\$PATH"
EOF

# Create symlinks
echo "🔗 Creating symlinks..."

ln -sf "$DOTFILES_DIR/zsh/.zshrc" "$HOME/.zshrc"

mkdir -p "$HOME/.config"
ln -sf "$DOTFILES_DIR/zsh/starship.toml" "$HOME/.config/starship.toml"

# Set zsh as default shell
ZSH_PATH="$(which zsh)"
if [ "$SHELL" != "$ZSH_PATH" ]; then
    echo "🐚 Setting zsh as default shell..."
    chsh -s "$ZSH_PATH"
else
    echo "✓ zsh is already the default shell"
fi

echo ""
echo "✅ Dotfiles setup complete!"
echo ""
echo "To start using your new shell, run:"
echo "  exec zsh"

